# Generated by Django 4.1.4 on 2023-12-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/images/default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
