# Generated by Django 4.1.4 on 2023-12-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=20)),
                ('fee', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='specialists/images/')),
                ('description', models.TextField(blank=True, default='')),
                ('nmc_num', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('qualification', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='doctor_profile',
        ),
        migrations.AddField(
            model_name='specialist',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialist.category'),
        ),
    ]
