# Generated by Django 4.1.4 on 2023-12-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_email_profile_first_name_profile_last_name_and_more'),
        ('specialist', '0002_specialist_category_slug_delete_doctor_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.TimeField(blank=True, null=True)),
                ('tuesday', models.TimeField(blank=True, null=True)),
                ('wednesday', models.TimeField(blank=True, null=True)),
                ('thursday', models.TimeField(blank=True, null=True)),
                ('friday', models.TimeField(blank=True, null=True)),
                ('saturday', models.TimeField(blank=True, null=True)),
                ('sunday', models.TimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='specialist.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='specialist.specialist')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='users.profile')),
            ],
        ),
    ]
