# Generated by Django 4.1.4 on 2023-12-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0004_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
