# Generated by Django 4.1.4 on 2023-12-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_email_profile_first_name_profile_last_name_and_more'),
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseaseinfo',
            old_name='diseasename',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='diseaseinfo',
            old_name='symptomsname',
            new_name='symptoms',
        ),
        migrations.RemoveField(
            model_name='diseaseinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='diseaseinfo',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
