# Generated by Django 4.1.4 on 2023-12-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_rename_diseasename_diseaseinfo_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('meaning', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='symptoms/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('meaning', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='diseases/')),
                ('symptoms', models.ManyToManyField(blank=True, related_name='related_diseases', to='disease.symptom')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
