# Generated by Django 4.1.4 on 2023-12-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0004_disease_specialist_alter_disease_meaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diseases/'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='symptoms/'),
        ),
    ]
