# Generated by Django 4.1.4 on 2023-12-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_alter_disease_image_alter_symptom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinfo',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_diagnosed', to='disease.disease'),
        ),
    ]
