# Generated by Django 4.1.4 on 2023-12-30 10:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0005_delete_appointment'),
        ('users', '0005_profile_email_profile_first_name_profile_last_name_and_more'),
        ('disease', '0006_alter_diseaseinfo_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True)),
                ('symptoms', models.CharField(max_length=2000)),
                ('doctor_diagnosis', models.CharField(blank=True, max_length=255)),
                ('doctor_note', tinymce.models.HTMLField()),
                ('prescription', tinymce.models.HTMLField()),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('ai_diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='disease.diseaseinfo')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_booked', to='specialist.specialist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_booked', to='users.profile')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
