# Generated by Django 4.1.4 on 2023-12-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0007_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
